administrator/urls.py
from . import views

from django.urls import path

from administrator import views as GeneratePDF

app_name = "administrator"

urlpatterns = [

	path('', views.administrator, name='administrator'),
	path('session/', views.session, name='session'),
	path('add_session/', views.add_session, name='add_session'),
	path('register/', views.add_student, name='register'),
	path('add_result/', views.add_result, name='add_result'),
	path('query_result/', views.query_result, name='query_result'),
	path('query_general_result/', views.query_general_result, name='query_general_result'),
	path('generate_average/', views.generate_average, name='generate_average'),
	path('generate_result/', views.generate_result, name='generate_result'),
	path('add_student_result/<slug:pk>/', views.add_student_result, name='add_student_result'),
	path('term/', views.term, name='term'),
	path('addterm/', views.add_term, name='add_term'),
	path('pin/', views.pin, name='pin'),
	path('change_current_session/', views.change_current_session, name='change_current_session'),
	path('check_result/', views.check_result, name='check_result'),
	path('student_result/', views.student_result, name='student_result'),
	path('generatepin/', views.generatepin, name='generatepin'),
	path('pdf/', views.get_your_copy, name='get_your_copy'),
	path('updatenews/', views.NewsUpdate, name='news_update'),
	path('generate_course/', views.generate_course, name='generate_course'),
	path('promote/', views.QueryPromoteStudent, name='promote'),
	path('promote_student/', views.PromoteStudent, name='promote_student'),
	path('query_student/', views.query_student, name='query_student'),
	path('students/', views.students, name='students'),
	path('edit_student/<slug:id>/', views.edit_student, name='edit_student'),
	path('news/', views.news, name='news'),
	path('news/<slug:slug>/', views.newsdetails, name='newsdetails'),
	path('deletenews/<slug:slug>/', views.deletenews, name='deletenews'),
	path('editnews/<slug:slug>/', views.editnews, name='editnews'),

	path('query_student_term/', views.query_student_term, name='query_student_term'),
	path('change_student_term/', views.change_student_term, name='change_student_term'),
	path('select_student/', views.select_student, name='select_student'),
	path('query_staff_check_result/', views.query_staff_check_result, name='query_staff_check_result'),
	path('staff_check_result/', views.staff_check_result, name='staff_check_result'),
	path('edit_general_result/<slug:reg>', views.edit_general_result, name='edit_general_result'),

	path('gallery/', views.gallery, name='gallery'),
	path('payment/', views.addpayment, name='addpayment'),
	path('querypayment/', views.query_payment, name='query_payment'),
	path('checkpayment/', views.check_payment, name='check_payment'),
	path('selectpayment/', views.select_payment, name='select_payment'),
	path('editpayment/<slug:id>/', views.edit_payment, name='edit_payment'),
	path('birthday/', views.birthday_today, name='birthday_today'),
	path('exam/', views.Exam, name='exam'),
	path('timetable/', views.timetable, name='timetable'),
	path('assignment/', views.assignment, name='assignment'),
    path('feedback/', views.feedbackView, name='feedback'),
    





]

exam/urls.py
from . import views

from django.urls import path

from administrator import views as GeneratePDF

app_name = "exam"

urlpatterns = [

	path('', views.index, name='index'),
	path('dashboard/', views.dashboard, name='dashboard'),
	path('subjects/', views.subjects, name='subjects'),
	path('add_subject/', views.add_subject, name='add_subject'),
	path('delete_subject/<slug:id>/', views.delete_subject, name='delete_subject'),
	path('questions/', views.Questions, name='questions'),
	path('addquestions/', views.AddQuestions, name='addquestions'),
	path('deletequestions/', views.deleteQuestion, name='deletequestions'),
	path('startexam/', views.startexam, name='startexam'),
	
	
	
	
	
	
	



]

home/urls.py
from . import views

from django.urls import path



app_name = "home"

urlpatterns = [
	path('', views.home, name='home'),
	path('about/', views.about, name='about'),
    path('publication/', views.publicationView, name='publication'),
    path('publication/<int:id>/', views.publicationDetailView, name='publication_detail'),
	path('contact/', views.contact, name='contact'),
	path('price/', views.price, name='price'),
	path('blog/', views.blog, name='blog'),
	path('blogdetail/', views.blogdetail, name='blogdetail'),
	path('student_result/', views.student_result, name='student_result'),
	path('gallery/', views.gallery, name='gallery'),
	path('payment/', views.student_payment, name='student_payment'),
	path('check/', views.check_student_payment, name='check_student_payment'),
	path('payment_confirm/<slug:id>/', views.student_payment_confirm, name='student_payment'),
	# path('payment_confirm/<slug:reg>/<slug:purpose>/<slug:fee>/<slug:session>/<slug:student_class>/<slug:term>/', views.student_payment_confirm, name='student_payment'),

	# path('', views.gallery, name='gallery'),
	# path('', views.checkresult, name='checkresult'),
	# path('', views.portal, name='portal'),

	


]

school/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('index.urls')),
    path('', include('home.urls')),
    path('administrator/', include('administrator.urls')),
    path('accounts/', include('account.urls')),
    path('student/', include('student.urls')),
    path('exam/', include('exam.urls')),
    

    # path('home/', include('home.urls')),

    path('ckeditor/', include('ckeditor_uploader.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

home/forms.py
from django import forms

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from administrator.models import Payments, Session, Myclass, Student, StudentPayment, Student_subject, Subject, Term, GeneralResult, CurrentSession, CurrentTerm, GeneralResult, GeneratePin, SchoolLogo, News, Gallery

from administrator.forms import AddSessionForm, StudentForm, CurrentTermForm, CurrentSessionForm, CheckResultForm, NewsForm, EditGeneralResultForm, GalleryForm, StudentPaymentForm

from django.contrib import messages

from django.http import HttpResponseRedirect, HttpResponse,JsonResponse



def home(request):
	return render(request, 'index/index.html')
def about(request):
	return render(request, 'index/about.html')

def publicationView(request):
	qs = News.objects.all()
	context = {'qs':qs}
	return render(request, 'index/courses.html', context)

def publicationDetailView(request, id):
	qs = get_object_or_404(News, id=id)
	context = {'qs':qs}
	return render(request, 'index/course-detail.html', context)

def contact(request):
	return render(request, 'index/contact.html')
def price(request):
	return render(request, 'home/price.html')
def blog(request):
	return render(request, 'home/blog.html')
def blogdetail(request):
	return render(request, 'home/single-blog.html')
def gallery(request):
	return render(request, 'home/gallery.html')

def student_result(request):
	image = SchoolLogo.objects.get(id=1)
	session = Session.objects.all()
	if request.method=='POST':
		form = CheckResultForm(request.POST or None)
		if form.is_valid():
			reg = form.cleaned_data.get('Registration_Number')
			pin = form.cleaned_data.get('Pin')
			term = request.POST.get('term')
			t = Term.objects.get(term__iexact=term)
			try:
				# print(image)
				gen = GeneratePin.objects.get(Registration_Number=reg, pin=pin)
				result = GeneralResult.objects.get(Registration_Number=gen.Registration_Number, current_session=gen.current_session, current_class__iexact=gen.current_class, current_term__iexact=term, active=True)
				s = Session.objects.get(date=gen.current_session)
				# t = Term.objects.get(term=current_term.term)
				total_student = Student.objects.filter(current_class=gen.current_class, current_session=s.id, current_term=t.id ).count()
				record = Student_subject.objects.filter(Registration_Number=gen.Registration_Number).exclude(average=0)
				context={'gen':gen, 'result':result, 'record':record, 'total_student':total_student, 'image':image, 'reg':reg, 'pin':pin}
				return render(request, 'home/check_result.html', context)
			except GeneratePin.DoesNotExist:
				messages.error(request, 'Invalid Details')
				return redirect('home:student_result')
			except GeneralResult.DoesNotExist:
			    messages.error(request, 'Result does not exist')
			    return redirect('home:student_result')


	else:
		form = CheckResultForm()
	return render(request, 'home/student_result.html', {'form':form, 'image':image, 'session':session})




def student_payment(request):
	details = "Fill Payment Details"
	if request.method=='POST':
		form = StudentPaymentForm(request.POST)
		if form.is_valid():
			reg = form.cleaned_data.get('Registration_Number')
			current_class = form.cleaned_data.get('current_class')
			current_session = form.cleaned_data.get('current_session')
			current_term = form.cleaned_data.get('current_term')
			form.save()
			current_term = Term.objects.get(term=current_term).term.replace(' ', '-')
			purpose = form.cleaned_data.get('purpose').replace(' ', '-')
			try:

				student = Student.objects.get(Registration_Number=reg)

				print(student)
				userid = form.save()
				userid=userid.id



				# print(reg, current_class, current_session, current_term, purpose)
				context = {'userid':userid,'student':student, 'reg':reg, 'current_class':current_class, 'current_session':current_session, 'current_term':current_term, 'purpose':purpose}
				return render(request, 'home/paymentgateway.html', context)
			except Student.DoesNotExist:
				messages.error(request, 'Invalid Reg number')
				return render(request, 'home/paymenterror.html')
	else:
		form = StudentPaymentForm()
	return render(request, 'home/payment.html', {'form':form, 'details':details})



def student_payment_confirm(request, id):

	qs = StudentPayment.objects.get(id=id)
	qs.paid=True
	qs.save()
	print(qs.paid)

	# Payments.objects.create()
	# new_term = term.replace('-', ' ')
	# term = Term.objects.get(term = new_term)
	# session = Session.objects.get(date=session)
	# student = Student.objects.get(Registration_Number=reg)
	# purpose = purpose.replace('-', ' ')
	# session=session
	# Payments.objects.create(student=student, session=session, term=term, student_class=student_class, purpose=purpose, fee=fee)
	# print(term, session, student)
	context={}
	return render(request, 'home/student_payment_confirm.html', context)



def check_student_payment(request):
	details = "Check Payment Details"
	if request.method=='POST':
		form = StudentPaymentForm(request.POST or None)
		if form.is_valid():
			reg = form.cleaned_data.get('Registration_Number')
			current_class = form.cleaned_data.get('current_class')
			current_session = form.cleaned_data.get('current_session')
			current_term = form.cleaned_data.get('current_term')
			student_class = form.cleaned_data.get('current_class')
			purpose = form.cleaned_data.get('purpose')
			fee = form.cleaned_data.get('fee')

			term = Term.objects.get(term = current_term)
			session = Session.objects.get(date=current_session)
			student = Student.objects.get(Registration_Number=reg)
			session=session
			print(fee, purpose)

			# current_term = Term.objects.get(term=current_term).term.replace(' ', '-')

			# purpose = form.cleaned_data.get('purpose').replace(' ', '-')
			qs = StudentPayment.objects.filter(Registration_Number=reg, current_session=session, current_term=term, current_class=student_class, purpose=purpose)
			details=Student.objects.get(Registration_Number=reg)
			#qs = Payments.objects.filter(student=student, session=session, term=term, student_class=student_class, purpose=purpose, fee=fee)
			print(reg)
			if qs.exists():
				context= {"qs":qs, "details":details}
				return render(request, 'home/filteredpayment.html', context)
			else:
				return HttpResponse("not yet paid")
	else:
		form = StudentPaymentForm()
	return render(request, 'home/payment.html', {'form':form, "details":details})



# , purpose, fee, session, student_class, term




# def home(request):
# 	return render(request, 'home/index.html')
# def home(request):
# 	return render(request, 'home/index.html')
def todayBirthday(request):
	return render(request, 'todaybirthday.html')

templates/home/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="icon" href="img/favicon.png" type="image/png">
        <title>DEMO SCHOOL MANAGEMENT SYSTEM</title>
        <!-- Bootstrap CSS -->

        <link rel="stylesheet" href="{% static 'home/css/bootstrap.css' %}">
<!--         <link rel="stylesheet" href="css/bootstrap.css"> -->
<!--         <link rel="stylesheet" href="vendors/linericon/style.css"> -->
        <link rel="stylesheet" href="{% static 'home/vendors/linericon/style.css' %}">

<!--         <link rel="stylesheet" href="css/font-awesome.min.css"> -->

        <link rel="stylesheet" href="{% static 'home/css/font-awesome.min.css' %}">

<!--         <link rel="stylesheet" href="vendors/owl-carousel/owl.carousel.min.css"> -->

        <link rel="stylesheet" href="{% static 'home/vendors/owl-carousel/owl.carousel.min.css' %}">

<!--         <link rel="stylesheet" href="vendors/lightbox/simpleLightbox.css"> -->
        <link rel="stylesheet" href="{% static 'home/vendors/lightbox/simpleLightbox.css' %}">

<!--         <link rel="stylesheet" href="vendors/nice-select/css/nice-select.css">
 -->
        <link rel="stylesheet" href="{% static 'home/vendors/nice-select/css/nice-select.css' %}">

<!--         <link rel="stylesheet" href="vendors/animate-css/animate.css"> -->
        <link rel="stylesheet" href="{% static 'home/vendors/animate-css/animate.css' %}">

<!--         <link rel="stylesheet" href="vendors/popup/magnific-popup.css"> -->

        <link rel="stylesheet" href="{% static 'home/vendors/popup/magnific-popup.css' %}">
        <!-- main css -->
<!--         <link rel="stylesheet" href="css/style.css"> -->
        <link rel="stylesheet" href="{% static 'home/css/style.css' %}">

<!--         <link rel="stylesheet" href="css/responsive.css"> -->
        <link rel="stylesheet" href="{% static 'home/css/responsive.css' %}">
    </head>
    <body>

        <!--================Header Menu Area =================-->
        <header class="header_area">
            <div class="top_menu row m0">
                <div class="container">
                    <div class="float-left">
                        <ul class="list header_social">
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                            <li><a href="#"><i class="fa fa-behance"></i></a></li>
                        </ul>
                    </div>
                    <div class="float-right">
                        <a class="dn_btn" href="tel:+4400123654896">+2349032841265</a>
                        <a class="dn_btn" href="mailto:support@colorlib.com">gospeltruth18@gmail.com</a>
                    </div>
                </div>
            </div>
            <div class="main_menu">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <div class="container">
                        <!-- Brand and toggle get grouped for better mobile display -->
                       <a class="navbar-brand logo_h" href="{% url 'home:home' %}"><img src="{% static 'home/img/schoolauto.png' %}" alt="" style="width: 200px; margin-top: -19px;"></a>
                       <!--  <a class="navbar-brand logo_h" href="{% url 'home:home' %}"><b>SCHOOL</b></a> -->

                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <!-- Collect the nav links, forms, and other content for toggling -->
{% url 'home:home' as home %}
{% url 'home:contact' as contact %}
{% url 'home:about' as about %}
{% url 'home:price' as price %}
{% url 'home:blog' as blog %}
{% url 'home:student_result' as student_result %}
{% url 'home:gallery' as gallery %}
                        <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                            <ul class="nav navbar-nav menu_nav ml-auto">
                                <li class="nav-item {% if request.path == home %}active{% endif %}"><a class="nav-link" href="{% url 'home:home' %}">Home</a></li>
                                <li class="nav-item {% if request.path == about %}active{% endif %}"><a class="nav-link" href="{% url 'home:about' %}">About</a></li>

      <!-- <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Payments <i class="fa fa-caret-down"></i>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'home:student_payment' %}">PAY FEES</a>
          <a class="dropdown-item" href="{% url 'home:check_student_payment' %}">CHECK PAYMENT DETAILS</a>

        </div>
      </li> -->



                                <li class="nav-item {% if request.path == contact %}active{% endif %} "><a class="nav-link" href="{% url 'home:contact' %}">Contact Us</a></li>


                                <!-- <li class="nav-item {% if request.path == price %}active{% endif %} "><a class="nav-link" href="{% url 'home:price' %}">Price</a></li> -->
                                <li class="nav-item {% if request.path == blog %}active{% endif %}"><a class="nav-link" href="{% url 'home:blog' %}">Blog</a></li>
                                <!-- <li class="nav-item {% if request.path == gallery %}active{% endif %} "><a class="nav-link" href="{% url 'home:gallery' %}">Gallery</a></li> -->
                                <!-- <li class="nav-item {% if request.path == student_result %}active{% endif %}"><a class="nav-link" href="{% url 'home:student_result' %}">Check Result</a></li> -->
                                <!-- <li class="nav-item"><a class="nav-link" href="{% url 'administrator:administrator' %}">Portal</a></li> -->



                            </ul>
                        </div>
                    </div>
                </nav>
            </div>
        </header>


{% block body %}
{% endblock %}







        <!--================ start footer Area  =================-->
        <footer class="footer-area p_120">
            <div class="container">
                <div class="row">
                    <div class="col-lg-2  col-md-6 col-sm-6">
                        <div class="single-footer-widget tp_widgets">
                           <h6 class="footer_title">Categories</h6>
                            <ul class="list">
                                <li><a href="#">Kindergaten</a></li>
                                <li><a href="#">Primary School</a></li>
                                <li><a href="#">Junior Secondary School</a></li>
                                <li><a href="#">Senior Secondary School</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-2  col-md-6 col-sm-6">
                        <div class="single-footer-widget tp_widgets">
                           <h6 class="footer_title">Contact Us</h6>
                              <p>
                                 <span style="color: white;">Address: </span> <br>
                                 20, Izekor Street, Off Uselu Lagos Road
                              </p>
                              <p>
                                  <span style="color: white;">Email: </span> <br>
                                   gospeltruth18@gmail.com
                              </p>
                              <p>
                                  <span style="color: white;">Tel: </span> <br>
                                   +2349032841265
                              </p>
                        </div>
                    </div>



                </div>
                <div class="row footer-bottom d-flex justify-content-between align-items-center">
                    <p class="col-lg-8 col-md-8 footer-text m-0"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
<!-- Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a> -->
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                    <div class="col-lg-4 col-md-4 footer-social">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-dribbble"></i></a>
                        <a href="#"><i class="fa fa-behance"></i></a>
                    </div>
                </div>
            </div>
        </footer>
        <!--================ End footer Area  =================-->






        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->

 <!--        <script src="js/jquery-3.3.1.min.js"></script> -->
         <script src="{% static 'home/js/jquery-3.3.1.min.js' %}"></script>

<!--         <script src="js/popper.js"></script> -->
        <script src="{% static 'home/js/popper.js' %}"></script>

<!--         <script src="js/bootstrap.min.js"></script> -->

        <script src="{% static 'home/js/bootstrap.min.js' %}"></script>
<!--         <script src="js/stellar.js"></script> -->

        <script src="{% static 'home/js/stellar.js' %}"></script>

<!--         <script src="vendors/lightbox/simpleLightbox.min.js"></script> -->
        <script src="{% static 'home/vendors/lightbox/simpleLightbox.min.js' %}"></script>


<!--         <script src="vendors/nice-select/js/jquery.nice-select.min.js"></script> -->
        <script src="{% static 'home/vendors/nice-select/js/jquery.nice-select.min.js' %}"></script>


<!--         <script src="vendors/isotope/imagesloaded.pkgd.min.js"></script> -->

        <script src="{% static 'home/vendors/isotope/imagesloaded.pkgd.min.js' %}"></script>
<!--
        <script src="vendors/isotope/isotope.pkgd.min.js"></script> -->

        <script src="{% static 'home/vendors/isotope/isotope.pkgd.min.js' %}"></script>


<!--         <script src="vendors/owl-carousel/owl.carousel.min.js"></script> -->
       <script src="{% static 'home/vendors/owl-carousel/owl.carousel.min.js' %}"></script>

<!--
        <script src="vendors/popup/jquery.magnific-popup.min.js"></script> -->

       <script src="{% static 'home/vendors/popup/jquery.magnific-popup.min.js' %}"></script>

<!--
        <script src="js/jquery.ajaxchimp.min.js"></script> -->
       <script src="{% static 'home/js/jquery.ajaxchimp.min.js' %}"></script>


  <!--       <script src="vendors/counter-up/jquery.waypoints.min.js"></script> -->
       <script src="{% static 'home/vendors/counter-up/jquery.waypoints.min.js' %}"></script>


<!--         <script src="vendors/counter-up/jquery.counterup.js"></script> -->

       <script src="{% static 'home/vendors/counter-up/jquery.counterup.js' %}"></script>
<!--         <script src="js/mail-script.js"></script> -->

       <script src="{% static 'home/js/mail-script.js' %}"></script>
<!--         <script src="js/theme.js"></script> -->

       <script src="{% static 'home/js/theme.js' %}"></script>
    </body>
</html>

templates/home/blog.html
{% extends 'home/base.html' %}
{% load static %}
{% block body %}
        <!--================Header Menu Area =================-->
        

        

        
        <!--================Latest Blog Area =================-->
        <section class="latest_blog_area p_120">
        	<div class="container">
        		<div class="main_title">
        			<h2>Latest Posts From Blog</h2>
        			<p>There is a moment in the life of any aspiring astronomer that it is time to buy that first telescope. It’s exciting to think about setting up your own viewing station.</p>
        		</div>
        		<div class="row latest_blog_inner">
        			<div class="col-lg-3 col-md-6">
        				<div class="l_blog_item"> 
        					<img class="img-fluid" src="{% static 'home/img/latest-blog/l-blog-1.jpg' %}" alt="">
        					<a class="date" href="#">25 October, 2018  |  By Mark Wiens</a>
        					<a href="{% url 'home:blogdetail' %}"><h4>Addiction When Gambling Becomes A Problem</h4></a>
 <!--        					<p>Computers have become ubiquitous in almost every facet of our lives. At work, desk jockeys spend hours in front of their desktops, while delivery</p> -->
        				</div>
        			</div>
        			<div class="col-lg-3 col-md-6">
        				<div class="l_blog_item">
        					<img class="img-fluid" src="{% static 'home/img/latest-blog/l-blog-2.jpg' %}" alt="">
        					<a class="date" href="#">25 October, 2018  |  By Mark Wiens</a>
        					<a href="{% url 'home:blogdetail' %}"><h4>Addiction When Gambling Becomes A Problem</h4></a>
       <!--  					<p>Computers have become ubiquitous in almost every facet of our lives. At work, desk jockeys spend hours in front of their desktops, while delivery</p> -->
        				</div>
        			</div>
        			<div class="col-lg-3 col-md-6">
        				<div class="l_blog_item">
        					<img class="img-fluid" src="{% static 'home/img/latest-blog/l-blog-3.jpg' %}" alt="">
        					<a class="date" href="#">25 October, 2018  |  By Mark Wiens</a>
        					<a href="{% url 'home:blogdetail' %}"><h4>Addiction When Gambling Becomes A Problem</h4></a>
<!--         					<p>Computers have become ubiquitous in almost every facet of our lives. At work, desk jockeys spend hours in front of their desktops, while delivery</p> -->
        				</div>
        			</div>
        			<div class="col-lg-3 col-md-6">
        				<div class="l_blog_item">
        					<img class="img-fluid" src="{% static 'home/img/latest-blog/l-blog-4.jpg' %}" alt="">
        					<a class="date" href="#">25 October, 2018  |  By Mark Wiens</a>
        					<a href="{% url 'home:blogdetail' %}"><h4>Addiction When Gambling Becomes A Problem</h4></a>
<!--         					<p>Computers have become ubiquitous in almost every facet of our lives. At work, desk jockeys spend hours in front of their desktops, while delivery</p> -->
        				</div>
        			</div>
        		</div>
        	</div>
        </section>
        <!--================End Latest Blog Area =================-->
        

{% endblock %}

templates/home/contact.html
{% extends 'home/base.html' %}
{% load static %}
{% block body %}
        <!--================Header Menu Area =================-->
        
        <!--================Home Banner Area =================-->
        <section class="banner_area">
            <div class="banner_inner d-flex align-items-center">
            	<div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
				<div class="container">
					<div class="banner_content text-center">
						<h2>Contact Us</h2>
						<div class="page_link">
							<a href="{% url 'home:home' %}">Home</a>
							<a href="{% url 'home:contact' %}">Contact</a>
						</div>
					</div>
				</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->
        
        <!--================Contact Area =================-->
        <section class="contact_area p_120">
            <div class="container">
                <!-- <div id="mapBox" class="mapBox" 
                    data-lat="40.701083" 
                    data-lon="-74.1522848" 
                    data-zoom="13" 
                    data-info="PO Box CT16122 Collins Street West, Victoria 8007, Australia."
                    data-mlat="40.701083"
                    data-mlon="-74.1522848">
                </div> -->
                <div class="row">
                    <div class="col-lg-3">
                        <div class="contact_info">
                            <div class="info_item">
                                <i class="lnr lnr-home"></i>
                                <h6>Benin City, Nigeria</h6>
                                <p>20, Izekor Street, Off Uselu Lagos Road</p>
                            </div>
                            <div class="info_item">
                                <i class="lnr lnr-phone-handset"></i>
                                <h6><a href="#">+2349032841265</a></h6>
                                <p>Mon to Fri 8am to 6 pm</p>
                            </div>
                            <div class="info_item">
                                <i class="lnr lnr-envelope"></i>
                                <h6><a href="#">gospeltruth18@gmail.com</a></h6>
                                <p>Send us your query anytime!</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-9">
                        <form class="row contact_form" action="contact_process.php" method="post" id="contactForm" novalidate="novalidate">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="text" class="form-control" id="name" name="name" placeholder="Enter your name">
                                </div>
                                <div class="form-group">
                                    <input type="email" class="form-control" id="email" name="email" placeholder="Enter email address">
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" id="subject" name="subject" placeholder="Enter Subject">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <textarea class="form-control" name="message" id="message" rows="1" placeholder="Enter Message"></textarea>
                                </div>
                            </div>
                            <div class="col-md-12 text-right">
                                <button type="submit" value="submit" class="btn submit_btn">Send Message</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        <!--================Contact Area =================-->
        
        <!--================ start footer Area  =================-->	
{% endblock %}