administrator/urls.py
from . import views

from django.urls import path

from administrator import views as GeneratePDF

app_name = "administrator"

urlpatterns = [

	path('', views.administrator, name='administrator'),
	path('session/', views.session, name='session'),
	path('add_session/', views.add_session, name='add_session'),
	path('register/', views.add_student, name='register'),
	path('add_result/', views.add_result, name='add_result'),
	path('query_result/', views.query_result, name='query_result'),
	path('query_general_result/', views.query_general_result, name='query_general_result'),
	path('generate_average/', views.generate_average, name='generate_average'),
	path('generate_result/', views.generate_result, name='generate_result'),
	path('add_student_result/<slug:pk>/', views.add_student_result, name='add_student_result'),
	path('term/', views.term, name='term'),
	path('addterm/', views.add_term, name='add_term'),
	path('pin/', views.pin, name='pin'),
	path('change_current_session/', views.change_current_session, name='change_current_session'),
	path('check_result/', views.check_result, name='check_result'),
	path('student_result/', views.student_result, name='student_result'),
	path('generatepin/', views.generatepin, name='generatepin'),
	path('pdf/', views.get_your_copy, name='get_your_copy'),
	path('updatenews/', views.NewsUpdate, name='news_update'),
	path('generate_course/', views.generate_course, name='generate_course'),
	path('promote/', views.QueryPromoteStudent, name='promote'),
	path('promote_student/', views.PromoteStudent, name='promote_student'),
	path('query_student/', views.query_student, name='query_student'),
	path('students/', views.students, name='students'),
	path('edit_student/<slug:id>/', views.edit_student, name='edit_student'),
	path('news/', views.news, name='news'),
	path('news/<slug:slug>/', views.newsdetails, name='newsdetails'),
	path('deletenews/<slug:slug>/', views.deletenews, name='deletenews'),
	path('editnews/<slug:slug>/', views.editnews, name='editnews'),

	path('query_student_term/', views.query_student_term, name='query_student_term'),
	path('change_student_term/', views.change_student_term, name='change_student_term'),
	path('select_student/', views.select_student, name='select_student'),
	path('query_staff_check_result/', views.query_staff_check_result, name='query_staff_check_result'),
	path('staff_check_result/', views.staff_check_result, name='staff_check_result'),
	path('edit_general_result/<slug:reg>', views.edit_general_result, name='edit_general_result'),

	path('gallery/', views.gallery, name='gallery'),
	path('payment/', views.addpayment, name='addpayment'),
	path('querypayment/', views.query_payment, name='query_payment'),
	path('checkpayment/', views.check_payment, name='check_payment'),
	path('selectpayment/', views.select_payment, name='select_payment'),
	path('editpayment/<slug:id>/', views.edit_payment, name='edit_payment'),
	path('birthday/', views.birthday_today, name='birthday_today'),
	path('exam/', views.Exam, name='exam'),
	path('timetable/', views.timetable, name='timetable'),
	path('assignment/', views.assignment, name='assignment'),
    path('feedback/', views.feedbackView, name='feedback'),
    





]

exam/urls.py
from . import views

from django.urls import path

from administrator import views as GeneratePDF

app_name = "exam"

urlpatterns = [

	path('', views.index, name='index'),
	path('dashboard/', views.dashboard, name='dashboard'),
	path('subjects/', views.subjects, name='subjects'),
	path('add_subject/', views.add_subject, name='add_subject'),
	path('delete_subject/<slug:id>/', views.delete_subject, name='delete_subject'),
	path('questions/', views.Questions, name='questions'),
	path('addquestions/', views.AddQuestions, name='addquestions'),
	path('deletequestions/', views.deleteQuestion, name='deletequestions'),
	path('startexam/', views.startexam, name='startexam'),
	
	
	
	
	
	
	



]

home/urls.py
from . import views

from django.urls import path



app_name = "home"

urlpatterns = [
	path('', views.home, name='home'),
	path('about/', views.about, name='about'),
    path('publication/', views.publicationView, name='publication'),
    path('publication/<int:id>/', views.publicationDetailView, name='publication_detail'),
	path('contact/', views.contact, name='contact'),
	path('price/', views.price, name='price'),
	path('blog/', views.blog, name='blog'),
	path('blogdetail/', views.blogdetail, name='blogdetail'),
	path('student_result/', views.student_result, name='student_result'),
	path('gallery/', views.gallery, name='gallery'),
	path('payment/', views.student_payment, name='student_payment'),
	path('check/', views.check_student_payment, name='check_student_payment'),
	path('payment_confirm/<slug:id>/', views.student_payment_confirm, name='student_payment'),
	# path('payment_confirm/<slug:reg>/<slug:purpose>/<slug:fee>/<slug:session>/<slug:student_class>/<slug:term>/', views.student_payment_confirm, name='student_payment'),

	# path('', views.gallery, name='gallery'),
	# path('', views.checkresult, name='checkresult'),
	# path('', views.portal, name='portal'),

	


]

index/urls.py
from . import views

from django.urls import path



app_name = "index"

urlpatterns = [
	path('', views.index, name='index'),
	path('about/', views.about, name='about'),
	path('contact/', views.contact, name='contact'),
	path('price/', views.price, name='price'),
	path('news/', views.news, name='news'),
	path('gallery/', views.gallery, name='gallery'),
	path('gallery/', views.gallery, name='gallery'),
	path('news_detail/<slug:id>/', views.news_detail, name='news_detail'),
	


]

school/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('index.urls')),
    path('', include('home.urls')),
    path('administrator/', include('administrator.urls')),
    path('accounts/', include('account.urls')),
    path('student/', include('student.urls')),
    path('exam/', include('exam.urls')),
    

    # path('home/', include('home.urls')),

    path('ckeditor/', include('ckeditor_uploader.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="free-educational-responsive-web-template-webEdu">
  <meta name="author" content="webThemez.com">
  <title>CreamCrest</title>
  <link rel="favicon" href="assets/images/favicon.png">

  <link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">


<!--  <link rel="stylesheet" href="assets/css/bootstrap.min.css">
  <link rel="stylesheet" href="assets/css/bootstrap.min.css"> -->
  <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">

<!--  <link rel="stylesheet" href="assets/css/font-awesome.min.css">  -->
  <link rel="stylesheet" href="{% static 'assets/css/font-awesome.min.css' %}">

<!--  <link rel="stylesheet" href="assets/css/bootstrap-theme.css" media="screen">  -->
  <link rel="stylesheet" href="{% static 'assets/css/bootstrap-theme.css' %}" media="screen"> 

<!--  <link rel="stylesheet" href="assets/css/style.css"> -->
  <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">

<!--     <link rel='stylesheet' id='camera-css'  href='assets/css/camera.css' type='text/css' media='all'>  -->
  <link rel="stylesheet" id='camera-css'  href="{% static 'assets/css/camera.css' %}" type='text/css' media='all'>

  <style>
      @media only screen and (min-width: 768px) {
    /* For desktop: */}


@media only screen and (max-width: 768px) {
    /* For mobile phones: */
    #logo{
      margin-top: 2px;
    }

}




  </style>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="assets/js/html5shiv.js"></script>
  <script src="assets/js/respond.min.js"></script>
  <![endif]-->

{% url 'index:index' as home %}
{% url 'index:contact' as contact %}
{% url 'index:about' as about %}
{% url 'index:price' as price %}
{% url 'index:news' as news %}
{% url 'administrator:student_result' as student_result %}
{% url 'index:gallery' as gallery %}

</head>
<body>
  <!-- Fixed navbar -->
  <div class="navbar navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <!-- Button for smallest screens -->
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
        <a class="navbar-brand" href="{% url 'index:index' %}">
          <img src="{% static 'img/Creamcreast.png' %}"  alt="logo" style="" id="logo">
        <!-- <img src="{% static 'assets/images/logo.png' %}"  alt="logo"> -->
          <!-- <img src="assets/images/logo.png" alt="Techro HTML5 template"> --></a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav pull-right mainNav">
          <li class=""><a href="{% url 'index:index' %}">Home</a></li>
          <li {% if request.path == about %}class="active"{% endif %} ><a href="{% url 'index:about' %}">About</a></li>
          <li {% if request.path == news %}class="active"{% endif %}><a href="{% url 'index:news' %}">News</a></li>
          <li {% if request.path == contact %}class="active"{% endif %}><a href="{% url 'index:contact' %}">Contact Us</a></li>
          <li {% if request.path == price %}class="active"{% endif %}><a href="{% url 'index:price' %}">Price</a></li>
          <li {% if request.path == gallery %}class="active"{% endif %}><a href="{% url 'index:gallery' %}">Gallery</a></li>

          <li><a href="{% url 'administrator:administrator' %}">Portal</a></li>
          <li {% if request.path == student_result %}class="active"{% endif %}><a href="{% url 'administrator:student_result' %}">Check Result</a></li>

        </ul>
      </div>
      <!--/.nav-collapse -->
    </div>
  </div>
  <!-- /.navbar -->


{% block body %}

{% endblock %}   
  

      



  <footer id="footer">
 
    <div class="container">
   <div class="row">
  <div class="footerbottom">
<!--     <div class="col-md-3 col-sm-6">
      <div class="footerwidget">
        <h4>
          Course Categories
        </h4>
        <div class="menu-course">
          <ul class="menu">
            <li><a href="#">
                List of Technology 
              </a>
            </li>
            <li><a href="#">
                List of Business
              </a>
            </li>
            <li><a href="#">
                List of Photography
              </a>
            </li>
            <li><a href="#">
               List of Language
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div> -->
    <div class="col-md-3 col-sm-6">
      <div class="footerwidget">
        <h4>
         Categories
        </h4>
        <div class="menu-course">
          <ul class="menu">
            <li> <a href="#">
                Kindergaten </a>
            </li>
            <li><a href="#">
                Primary School
              </a>
            </li>
            <li><a href="#">
                Junior Secondary School
              </a>
            </li>
            <li><a href="#">
                Senior Secondary School
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
<!--     <div class="col-md-3 col-sm-6">
      <div class="footerwidget">
        <h4>
          Browse by Categories
        </h4>
        <div class="menu-course">
          <ul class="menu">
            <li><a href="#">
                All Classes
              </a>
            </li>
            <li> <a href="#">
                All Instructors
              </a>
            </li>
            <li><a href="#">
                All Members
              </a>
            </li>
            <li>
              <a href="#">
                All Groups
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div> -->
    <div class="col-md-3 col-sm-6"> 
              <div class="footerwidget"> 
                         <h4>Contact</h4> 
                        <p>Lorem reksi this dummy text unde omnis iste natus error sit volupum</p>
            <div class="contact-info"> 
            <i class="fa fa-map-marker"></i> Kerniles 416  - United Kingdom<br>
            <i class="fa fa-phone"></i>+00 123 156 711 <br>
             <i class="fa fa-envelope-o"></i> youremail@email.com
              </div> 
                </div><!-- end widget --> 
    </div>
  </div>
</div>
      <div class="social text-center">
        <a href="#"><i class="fa fa-twitter"></i></a>
        <a href="#"><i class="fa fa-facebook"></i></a>
        <a href="#"><i class="fa fa-dribbble"></i></a>
        <a href="#"><i class="fa fa-flickr"></i></a>
        <a href="#"><i class="fa fa-github"></i></a>
      </div>

      <div class="clear"></div>
      <!--CLEAR FLOATS-->
    </div>
<!--     <div class="footer2">
      <div class="container">
        <div class="row">

          <div class="col-md-6 panel">
            <div class="panel-body">
              <p class="simplenav">
                <a href="index.html">Home</a> | 
                <a href="about.html">About</a> |
                <a href="courses.html">Courses</a> |
                <a href="price.html">Price</a> |
                <a href="videos.html">Videos</a> |
                <a href="contact.html">Contact</a>
              </p>
            </div>
          </div>

          <div class="col-md-6 panel">
            <div class="panel-body">
              <p class="text-right">
                Copyright &copy; 2014. Template by <a href="http://webthemez.com/" rel="develop">WebThemez.com</a>
              </p>
            </div>
          </div>

        </div>
        
      </div>
    </div> -->
  </footer>
       


  <!-- JavaScript libs are placed at the end of the document so the pages load faster -->

  <script src="{% static 'assets/js/modernizr-latest.js' %}"></script> 


  <script type='text/javascript' src="{% static 'assets/js/jquery.min.js' %}"></script>

    <script type='text/javascript' src="{% static 'assets/js/fancybox/jquery.fancybox.pack.js' %}"></script>
    
    <script type='text/javascript' src="{% static 'assets/js/jquery.mobile.customized.min.js' %}"></script>

    <script type='text/javascript' src="{% static 'assets/js/jquery.easing.1.3.js' %}"></script> 

    <script type='text/javascript' src="{% static 'assets/js/camera.min.js' %}"></script> 

    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script> 

  <script src="{% static 'assets/js/custom.js' %}"></script>

    <script>
    jQuery(function(){
      
      jQuery('#camera_wrap_4').camera({
                transPeriod: 500,
                time: 3000,
        height: '600',
        loader: 'false',
        pagination: true,
        thumbnails: false,
        hover: false,
                playPause: false,
                navigation: false,
        opacityOnGrid: false,
        imagePath: 'assets/images/'
      });

    });
      
  </script>
    
</body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}

<!DOCTYPE html>
<html lang="en">
<head>

</head>

<body>


		<header id="head" class="secondary">
            <div class="container">
                    <h1>Contact Us</h1>
                    <!-- <p>Lorem ipsum dolor sit amet, consectetur adipiscing eliras scele!</p> -->
                </div>
    </header>


	<!-- container -->
	<div class="container">
				<div class="row">
					<div class="col-md-8">
						<h3 class="section-title">Your Message</h3>
						<p>
						Lorem Ipsum is inting and typesetting in simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the is dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
						</p>
						
						<form class="form-light mt-20" role="form">
							<div class="form-group">
								<label>Name</label>
								<input type="text" class="form-control" placeholder="Your name">
							</div>
							<div class="row">
								<div class="col-md-6">
									<div class="form-group">
										<label>Email</label>
										<input type="email" class="form-control" placeholder="Email address">
									</div>
								</div>
								<div class="col-md-6">
									<div class="form-group">
										<label>Phone</label>
										<input type="text" class="form-control" placeholder="Phone number">
									</div>
								</div>
							</div>
							<div class="form-group">
								<label>Subject</label>
								<input type="text" class="form-control" placeholder="Subject">
							</div>
							<div class="form-group">
								<label>Message</label>
								<textarea class="form-control" id="message" placeholder="Write you message here..." style="height:100px;"></textarea>
							</div>
							<button type="submit" class="btn btn-two">Send message</button><p><br/></p>
						</form>
					</div>
					<div class="col-md-4">
						<div class="row">
							<div class="col-md-6">
								<h3 class="section-title">Office Address</h3>
								<div class="contact-info">
									<h5>Address</h5>
									<p>5th Street, Carl View - United States</p>
									
									<h5>Email</h5>
									<p>info@webthemez.com</p>
									
									<h5>Phone</h5>
									<p>+09 123 1234 123</p>
								</div>
							</div> 
						</div> 						
					</div>
				</div>
			</div>
	<!-- /container -->

	
		{% endblock %}

</body>
</html>

templates/gallery.html
{% extends 'base.html' %}
{% block body %}


 	{% endblock %}  

templates/news.html
{% extends 'base.html' %}
{% block body %}
<!DOCTYPE html>
<html lang="en"> 
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="free-educational-responsive-web-template-webEdu">

</head>

<body>


 	<header id="head" class="secondary">
            <div class="container">
                    <h1>Latest News Update</h1>
                    <!-- <p>Lorem ipsum dolor sit amet, consectetur adipiscing eliras scele!</p> -->
                </div>
    </header>
    
    <!-- container -->
    <div class="container" style="margin-top: 30px;">
        <div class="row">
            {% for i in detail %}
            <a href="{% url 'index:news_detail' i.id %}">
            <div class="col-sm-3">
                 <img src="{{i.image.url}}" class="img-responsive" alt="bude.jpg" style=""><br>
                 <p>{{i.title}}</p>
                 <p>{{i.body|safe|truncatewords:30}}</p>

            </div>
            </a>
            {% endfor %}

        </div>
    </div>
    <!-- /container -->


</body>
</html>
{% endblock %}

templates/newsdetail.html
{% extends 'base.html' %}
{% block body %}
<div class="cotainer">
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">
			<img src="{{detail.image.url}}" alt="media">
				<div class="social">
				<a href="#"><i class="fa fa-twitter"></i></a>
				<a href="#"><i class="fa fa-facebook"></i></a>
				</div>

			<p>
				Title: {{detail.title}}
			</p>
			<p>
				Date: {{detail.timestamp}}
			</p>
			<p>
				{{detail.body|safe}}
			</p>
		</div>
		
	</div>
	
</div>

{% endblock %}  

templates/price.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="free-educational-responsive-web-template-webEdu">
	<meta name="author" content="webThemez.com">
	<title>About - Techro Bootstrap template</title>
	<link rel="favicon" href="assets/images/favicon.png">
	<link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
	<link rel="stylesheet" href="assets/css/bootstrap.min.css">
	<link rel="stylesheet" href="assets/css/font-awesome.min.css">
	<!-- Custom styles for our template -->
	<link rel="stylesheet" href="assets/css/bootstrap-theme.css" media="screen">
	<link rel="stylesheet" href="assets/css/style.css">
	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
	<script src="assets/js/html5shiv.js"></script>
	<script src="assets/js/respond.min.js"></script>
	<![endif]-->
</head>

<body>


		<header id="head" class="secondary">
            <div class="container">
                    <h1>Our Price</h1>
                 <!--    <p>Lorem ipsum dolor sit amet, consectetur adipiscing eliras scele!</p> -->
                </div>
    </header>


	<!-- container -->
	<div class="container">
		<div class="row">
			<!-- Article content -->
			<section class="col-sm-12 maincontent">
				<h3>Cost</h3>
				<p>
					Below is our fee for different classes
				</p>

			</section>
		</div>
	</div>
	<!-- /container -->

	<section class="container">
		<div class="heading">
			<!-- Heading -->
<!-- 			<h3>Range</h3>
			<p>At lorem Ipsum available, but the majority have suffered alteration in some form by injected humour.</p> -->
			<br />
		</div>
		<div class="row flat">
			<div class="col-lg-3 col-md-3 col-xs-6">
				<ul class="plan plan1">
					<li class="plan-name">Kindergaten
					</li>
					<li class="plan-price">
						<strong>#10, 000</strong> School Fees
					</li>
					<li>
						<strong>#3, 000</strong> P.T.A
					</li>
					<li>
						<strong>#2,000</strong> lesson Fee
					</li>

			<!-- 		<li class="plan-action">
						<a href="#" class="btn">Signup</a>
					</li> -->
				</ul>
			</div>

			<div class="col-lg-3 col-md-3 col-xs-6">
				<ul class="plan plan1">
					<li class="plan-name">Primary School
					</li>
					<li class="plan-price">
						<strong>#15, 000</strong> School Fees
					</li>
					<li>
						<strong>#4, 000</strong> P.T.A
					</li>
					<li>
						<strong>#3,000</strong> lesson Fee
					</li>

			<!-- 		<li class="plan-action">
						<a href="#" class="btn">Signup</a>
					</li> -->
				</ul>
			</div>

			<div class="col-lg-3 col-md-3 col-xs-6">
								<ul class="plan plan1">
					<li class="plan-name">Junior Secondary
					</li>
					<li class="plan-price">
						<strong>#20, 000</strong> School Fees
					</li>
					<li>
						<strong>#5, 000</strong> P.T.A
					</li>
					<li>
						<strong>#4,000</strong> lesson Fee
					</li>

			<!-- 		<li class="plan-action">
						<a href="#" class="btn">Signup</a>
					</li> -->
				</ul>
			</div>

			<div class="col-lg-3 col-md-3 col-xs-6">
								<ul class="plan plan1">
					<li class="plan-name">Senior Secondary
					</li>
					<li class="plan-price">
						<strong>#25, 000</strong> School Fees
					</li>
					<li>
						<strong>#6, 000</strong> P.T.A
					</li>
					<li>
						<strong>#5,000</strong> lesson Fee
					</li>

			<!-- 		<li class="plan-action">
						<a href="#" class="btn">Signup</a>
					</li> -->
				</ul>
			</div>
		</div>
	</section>

</body>
</html>
{% endblock %}

templates/rough.html
{% extends 'home/base.html' %}
{% load static %}
{% block body %}
        <!--================Header Menu Area =================-->
        
        <!--================Home Banner Area =================-->
        <section class="banner_area">
            <div class="banner_inner d-flex align-items-center">
            	<div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
				<div class="container">
					<div class="banner_content text-center">
						<h2>About Us</h2>
						<div class="page_link">
							<a href="{% url 'home:home' %}">Home</a>
							<a href="{% url 'home:about' %}">About Us</a>
						</div>
					</div>
				</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->
        
        <!--================About Area =================-->
        <section class="about_area p_120">
        	<div class="container">
        		<div class="main_title">
        			<h2>SchManager</h2>
        			<p>One of the most resourceful school in the country. Always striving for the best.</p>
        		</div>
        		<div class="row about_inner">
        			<div class="col-lg-6">
						<div class="accordion" id="accordionExample">
							<div class="card">
								<div class="card-header" id="headingOne">
									<button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
									Achievements
									<i class="lnr lnr-chevron-down"></i>
									<i class="lnr lnr-chevron-up"></i>
									</button>
								</div>

								<div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
									<div class="card-body">
									Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.
									</div>
								</div>
							</div>




						</div>
        			</div>
        			<div class="col-lg-6">
        				<div class="video_area" id="video">
							<img class="img-fluid" src="img/video-1.jpg" alt="">
							<a class="popup-youtube" href="#">
								<img src="img/icon/video-icon-1.png" alt="">
							</a>
						</div>
        			</div>
        		</div>
        		<div class="about_details">
<p>SchManager are renounced educational institutions known for its academic excellene and morally upright students. The school was founded by Mr. Bude in 199X.</p>

<p>The school is set up to develop the life of your young children with highly qualified staff, conducive learning environment with the state of the art facilities and dedication to moral values and godliness.
The school ensures a warm and welcoming environment that promotes mutual respect among staff and students</p>
        		</div>
        	</div>
        </section>
        <!--================End About Area =================-->
        
        <!--================Team Area =================-->
        <section class="team_area p_120">
        	<div class="container">
        		<div class="main_title">
        			<h2>Meet Our Staff</h2>
        			<p>There is a moment in the life of any aspiring astronomer that it is time to buy that first telescope. It’s exciting to think about setting up your own viewing station.</p>
        		</div>
        		<div class="row team_inner">
        			<div class="col-lg-3 col-sm-6">
        				<div class="team_item">
        					<div class="team_img">
        						<img class="rounded-circle" src="img/team/team-1.jpg" alt="">
        						<div class="hover">
        							<a href="#"><i class="fa fa-facebook"></i></a>
        							<a href="#"><i class="fa fa-twitter"></i></a>
        							<a href="#"><i class="fa fa-linkedin"></i></a>
        						</div>
        					</div>
        					<div class="team_name">
        						<h4>Ethel Davis</h4>
        						<p>Managing Director (Sales)</p>
        					</div>
        				</div>
        			</div>
        			<div class="col-lg-3 col-sm-6">
        				<div class="team_item">
        					<div class="team_img">
        						<img class="rounded-circle" src="img/team/team-2.jpg" alt="">
        						<div class="hover">
        							<a href="#"><i class="fa fa-facebook"></i></a>
        							<a href="#"><i class="fa fa-twitter"></i></a>
        							<a href="#"><i class="fa fa-linkedin"></i></a>
        						</div>
        					</div>
        					<div class="team_name">
        						<h4>Ethel Davis</h4>
        						<p>Managing Director (Sales)</p>
        					</div>
        				</div>
        			</div>
        			<div class="col-lg-3 col-sm-6">
        				<div class="team_item">
        					<div class="team_img">
        						<img class="rounded-circle" src="img/team/team-3.jpg" alt="">
        						<div class="hover">
        							<a href="#"><i class="fa fa-facebook"></i></a>
        							<a href="#"><i class="fa fa-twitter"></i></a>
        							<a href="#"><i class="fa fa-linkedin"></i></a>
        						</div>
        					</div>
        					<div class="team_name">
        						<h4>Ethel Davis</h4>
        						<p>Managing Director (Sales)</p>
        					</div>
        				</div>
        			</div>
        			<div class="col-lg-3 col-sm-6">
        				<div class="team_item">
        					<div class="team_img">
        						<img class="rounded-circle" src="img/team/team-4.jpg" alt="">
        						<div class="hover">
        							<a href="#"><i class="fa fa-facebook"></i></a>
        							<a href="#"><i class="fa fa-twitter"></i></a>
        							<a href="#"><i class="fa fa-linkedin"></i></a>
        						</div>
        					</div>
        					<div class="team_name">
        						<h4>Ethel Davis</h4>
        						<p>Managing Director (Sales)</p>
        					</div>
        				</div>
        			</div>
        		</div>
        	</div>
        </section>
        <!--================End Team Area =================-->

        

        
        <!--================ start footer Area  =================-->	
{% endblock %}