administrator/urls.py
from . import views

from django.urls import path

from administrator import views as GeneratePDF

app_name = "administrator"

urlpatterns = [

	path('', views.administrator, name='administrator'),
	path('session/', views.session, name='session'),
	path('add_session/', views.add_session, name='add_session'),
	path('register/', views.add_student, name='register'),
	path('add_result/', views.add_result, name='add_result'),
	path('query_result/', views.query_result, name='query_result'),
	path('query_general_result/', views.query_general_result, name='query_general_result'),
	path('generate_average/', views.generate_average, name='generate_average'),
	path('generate_result/', views.generate_result, name='generate_result'),
	path('add_student_result/<slug:pk>/', views.add_student_result, name='add_student_result'),
	path('term/', views.term, name='term'),
	path('addterm/', views.add_term, name='add_term'),
	path('pin/', views.pin, name='pin'),
	path('change_current_session/', views.change_current_session, name='change_current_session'),
	path('check_result/', views.check_result, name='check_result'),
	path('student_result/', views.student_result, name='student_result'),
	path('generatepin/', views.generatepin, name='generatepin'),
	path('pdf/', views.get_your_copy, name='get_your_copy'),
	path('updatenews/', views.NewsUpdate, name='news_update'),
	path('generate_course/', views.generate_course, name='generate_course'),
	path('promote/', views.QueryPromoteStudent, name='promote'),
	path('promote_student/', views.PromoteStudent, name='promote_student'),
	path('query_student/', views.query_student, name='query_student'),
	path('students/', views.students, name='students'),
	path('edit_student/<slug:id>/', views.edit_student, name='edit_student'),
	path('news/', views.news, name='news'),
	path('news/<slug:slug>/', views.newsdetails, name='newsdetails'),
	path('deletenews/<slug:slug>/', views.deletenews, name='deletenews'),
	path('editnews/<slug:slug>/', views.editnews, name='editnews'),

	path('query_student_term/', views.query_student_term, name='query_student_term'),
	path('change_student_term/', views.change_student_term, name='change_student_term'),
	path('select_student/', views.select_student, name='select_student'),
	path('query_staff_check_result/', views.query_staff_check_result, name='query_staff_check_result'),
	path('staff_check_result/', views.staff_check_result, name='staff_check_result'),
	path('edit_general_result/<slug:reg>', views.edit_general_result, name='edit_general_result'),

	path('gallery/', views.gallery, name='gallery'),
	path('payment/', views.addpayment, name='addpayment'),
	path('querypayment/', views.query_payment, name='query_payment'),
	path('checkpayment/', views.check_payment, name='check_payment'),
	path('selectpayment/', views.select_payment, name='select_payment'),
	path('editpayment/<slug:id>/', views.edit_payment, name='edit_payment'),
	path('birthday/', views.birthday_today, name='birthday_today'),
	path('exam/', views.Exam, name='exam'),
	path('timetable/', views.timetable, name='timetable'),
	path('assignment/', views.assignment, name='assignment'),
    path('feedback/', views.feedbackView, name='feedback'),
    





]

exam/urls.py
from . import views

from django.urls import path

from administrator import views as GeneratePDF

app_name = "exam"

urlpatterns = [

	path('', views.index, name='index'),
	path('dashboard/', views.dashboard, name='dashboard'),
	path('subjects/', views.subjects, name='subjects'),
	path('add_subject/', views.add_subject, name='add_subject'),
	path('delete_subject/<slug:id>/', views.delete_subject, name='delete_subject'),
	path('questions/', views.Questions, name='questions'),
	path('addquestions/', views.AddQuestions, name='addquestions'),
	path('deletequestions/', views.deleteQuestion, name='deletequestions'),
	path('startexam/', views.startexam, name='startexam'),
	
	
	
	
	
	
	



]

home/urls.py
from . import views

from django.urls import path



app_name = "home"

urlpatterns = [
	path('', views.home, name='home'),
	path('about/', views.about, name='about'),
    path('publication/', views.publicationView, name='publication'),
    path('publication/<int:id>/', views.publicationDetailView, name='publication_detail'),
	path('contact/', views.contact, name='contact'),
	path('price/', views.price, name='price'),
	path('blog/', views.blog, name='blog'),
	path('blogdetail/', views.blogdetail, name='blogdetail'),
	path('student_result/', views.student_result, name='student_result'),
	path('gallery/', views.gallery, name='gallery'),
	path('payment/', views.student_payment, name='student_payment'),
	path('check/', views.check_student_payment, name='check_student_payment'),
	path('payment_confirm/<slug:id>/', views.student_payment_confirm, name='student_payment'),
	# path('payment_confirm/<slug:reg>/<slug:purpose>/<slug:fee>/<slug:session>/<slug:student_class>/<slug:term>/', views.student_payment_confirm, name='student_payment'),

	# path('', views.gallery, name='gallery'),
	# path('', views.checkresult, name='checkresult'),
	# path('', views.portal, name='portal'),

	


]

school/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('index.urls')),
    path('', include('home.urls')),
    path('administrator/', include('administrator.urls')),
    path('accounts/', include('account.urls')),
    path('student/', include('student.urls')),
    path('exam/', include('exam.urls')),
    

    # path('home/', include('home.urls')),

    path('ckeditor/', include('ckeditor_uploader.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

student/urls.py
from . import views

from django.urls import path



app_name = "student"

urlpatterns = [
	path('', views.Student, name='student'),
    path('feedback', views.feedbackView, name='feedback'),
    path('create_feedback', views.createFeedback, name='create_feedback'),
    path('delete_feedback/<int:id>', views.deleteFeedback, name='delete_feedback'),

	]

administrator/views.py
from django.shortcuts import render


from constants.constants import SEMESTER, LEVELS
from student.models import FeedbackModel


from .models import Session, Myclass, Student, Student_subject, Subject, Term,StudentPayment, GeneralResult, CurrentSession, CurrentTerm, GeneralResult, GeneratePin, SchoolLogo, News, Gallery, Payments

from .forms import AddSessionForm, StudentForm, CurrentTermForm,StudentPaymentForm, CurrentSessionForm, CheckResultForm, NewsForm, EditGeneralResultForm, GalleryForm, PaymentsForm

from django.shortcuts import render, get_object_or_404, redirect

from django.contrib import messages

from django.http import HttpResponseRedirect, HttpResponse,JsonResponse

from django.contrib.auth.models import User

import random

import string

from random import choice

from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from twilio.rest import Client




from django.http import HttpResponse

from django.views.generic import View

from school.utils import render_to_pdf #created in step 4

from django.template.loader import get_template

from django.urls import reverse
from datetime import date
from datetime import datetime


def term(request):
	current_term = CurrentTerm.objects.all()
	all_terms = SEMESTER


	# form = TermForm(request.POST or None)
	return render(request, 'administrator/term.html', {'current_term':current_term, 'all_terms':all_terms})
def add_term(request):
	if request.method == 'POST':
		form  = CurrentTermForm(request.POST)
		if form.is_valid():
			term = form.cleaned_data['term']
			try:
				detail =  CurrentTerm.objects.get(id=1)
				detail.term =term
				detail.save()
			except CurrentTerm.DoesNotExist:
				detail =  CurrentTerm.objects.create(id=1, term=term)


			return redirect('administrator:term')
	else:
		form = CurrentTermForm(request.POST or None)
	context = {'form':form}
	return render(request, 'administrator/addterm.html',context)

@login_required(login_url='/accounts/login/')
def administrator(request):
	# a = Student_subject.objects.all()
	# for i in a:
	# 	i.current_class = 'kg1'
	# 	i.save()
	# term = Term.objects.get(id=1)
	# session = Session.objects.get(id=2)
	# subject = Subject.objects.get(id=2)
	# a = User.objects.all()
	# for i in a:
	# 	if not i.is_staff:
	# 		user = User.objects.get(username=i.username)
	# 		student = Student.objects.get(user=user)
	# 		Student_subject.objects.create(student=student, Registration_Number=student.Registration_Number, subject=subject, session=session, term=term)
	# session = Session.objects.get(id=2)
	# for i in range(20):
	# 	a = User.objects.create_user(username=str(i)+'user', password=i, email=str(i)+'@gmail.com')
	# 	Student.objects.create(user=a, surname=i, first_name=i, Registration_Number=str(i), Phone=i, Address=i, Gender='Male', email=a.email, current_class='kg1', current_session=session, current_term='1st term', year=1999, month=1, day=1)
	if not request.user.is_staff:
		return redirect('student:student')
	else:



	# account_sid = 'ACd0ab7ae369764f8d6da41d76a8d224b1'
	# auth_token = '94879c7686211685102340eb53a8134e'
	# client = Client(account_sid, auth_token)

	# message = client.messages \
	# .create(
	#  body='EZE CHUKA, THE BUDESCODE LOCATED YOU!!',
	#  from_='+19894744088',
	#  to='+234 903 284 1265'
	# )

	# print(message.sid)
		return render(request, 'administrator/index.html', {})



def birthday_today(request):
	currentDay = datetime.now().day
	currentMonth = datetime.now().month
	qs = Student.objects.filter(month=currentMonth, day = currentDay)
	print(currentDay, currentMonth, qs)
	return render(request, 'administrator/birthday.html', {'qs':qs})
def session(request):
	current_session = CurrentSession.objects.all()
	session = Session.objects.all()
	context = {'session':session, 'current_session':current_session}
	return render(request, "administrator/session.html", context)

def add_session(request):
	current_session = CurrentSession.objects.all()
	if request.method == 'POST':
		form = AddSessionForm(request.POST or None, request.FILES or None)
		if form.is_valid():
			ok = form.save(commit = False)
			ok.save()
			messages.success(request, ok.date + ' ' + 'is successfully added.')
			return redirect('administrator:session')
	else:
		form = AddSessionForm(request.POST or None)
	context = {'form':form,}
	return render(request, "administrator/addsession.html", context)

def addpayment(request):

	if request.method == 'POST':
		form = StudentPaymentForm(request.POST or None, request.FILES or None)
		if form.is_valid():
			student = form.cleaned_data.get("student")
			session = form.cleaned_data.get("current_session")
			term = form.cleaned_data.get("current_term")
			student_class = form.cleaned_data.get("student_class")
			purpose = form.cleaned_data.get("purpose")
			fee = form.cleaned_data.get("fee")
			reg = form.cleaned_data.get('Registration_Number')
			student = Student.objects.get(Registration_Number=reg)
			qs = form.save(commit=False)
			qs.student = student
			qs.save()
			messages.success(request, str(student) + ' ' + purpose + ' payment is successfully paid' + ' for ' + str(session) + ", " + str(term))
			return render(request, "administrator/addpaymentsuccess.html")
	else:
		form = StudentPaymentForm(request.POST or None)
	context = {'form':form,}
	return render(request, "administrator/addpayment.html", context)

def query_payment(request):
	all_terms = SEMESTER
	all_sessions = Session.objects.all()
	context = {'all_terms':all_terms, 'all_sessions':all_sessions}
	return render(request, "administrator/querypayment.html", context)

def check_payment(request):
	current_term = request.POST.get('term')
	current_session = request.POST.get('session')
	current_class = request.POST.get('class')

	s = Session.objects.get(date=current_session)
	t = Term.objects.get(term=current_term)

	qs = StudentPayment.objects.filter(current_session=s, current_term=t, current_class=current_class)
	if qs.exists():
		context = {"qs":qs, 's':s, 't':t, 'current_class':current_class}
		return render(request, 'administrator/checkpayment.html', context)

	else:
		return render(request, 'administrator/checkpayment.html')


def select_payment(request):
	surname = request.POST.get('surname')
	firstname = request.POST.get('firstname')
	middename = request.POST.get('middename')
	registrationnumber = request.POST.get('registrationnumber')
	try:
		details=Student.objects.get(Registration_Number=registrationnumber)
	except:
		return HttpResponse('Invalid Reg number')

	if surname:
		qs = Payments.objects.filter(student__surname__icontains=surname)
		detail = surname
		searched = 'surname'
	elif firstname:
		qs = Payments.objects.filter(student__first_name__icontains=firstname)
		detail = firstname
		searched = 'firstname'
	elif middename:
		qs = Payments.objects.filter(student__middle_name__icontains=middename)
		detail = middename
		searched = 'middlename'
	elif registrationnumber:
		student = Student.objects.get(Registration_Number__iexact=registrationnumber)
		qs = StudentPayment.objects.filter(student=student)
		detail = registrationnumber
		searched = 'registration number'


	else:
		qs = 'none'
		detail = 'none'
		searched = 'none'
	context= {'qs':qs, 'detail':detail, 'searched':searched, "details":details}
	return render(request, 'administrator/select_payment.html', context)

def edit_payment(request, id):

	detail = StudentPayment.objects.get(id=id)
	if request.method == 'POST':
		form = StudentPaymentForm(request.POST or None, request.FILES or None, instance = detail)
		if form.is_valid():
			form.save()
			return render(request, 'administrator/payment_edit_success.html')
	else:
		form = StudentPaymentForm(instance = detail)

	context = {'form':form, 'detail':detail, "detail_id":id}
	return render(request, 'administrator/edit_payment.html', context)



def change_current_session(request):
	if request.method == 'POST':
		form  = CurrentSessionForm(request.POST or None)
		if form.is_valid():

			select = form.save(commit=False)
			# print(select.session)
			try:
				current_session = CurrentSession.objects.get(id=1)
				current_session.session = select.session
				current_session.save()
			except CurrentSession.DoesNotExist:
				current_session = CurrentSession.objects.create(id=1, session = select.session)

			messages.success(request,  'current session is successfully changed')
			return redirect('administrator:session')
	else:
		form = CurrentSessionForm(request.POST or None)
	context = {'form':form}
	return render(request, "administrator/change_current_session.html", context)


def add_student(request):
	if request.method == 'POST':
		form = StudentForm(request.POST or None, request.FILES or None)
		if form.is_valid():

			ok = form.save(commit = False)
			# print(ok.surname)

			username = form.cleaned_data['Registration_Number']
			email = form.cleaned_data['email']
			password = form.cleaned_data['password']
			first_name = form.cleaned_data['first_name']
			last_name = form.cleaned_data['last_name']

			user = User.objects.create_user(username=username, email=email, password=password, first_name=first_name, last_name=last_name)
			ok.user = user
			ok.save()
			messages.success(request, ok.surname + ' ' + ok.first_name + ' ' + 'was successfully Registered')

			# add_subject(ok.pk, ok)

			return redirect('administrator:register')
	else:
		form = StudentForm(request.POST or None)
	context = {"form": form} 
	return render(request, "administrator/register.html", context)

def feedbackView(request):
	qs = FeedbackModel.objects.all()
	context = {'qs':qs}
	return render(request, 'administrator/feedback.html', context)

def generate_course(request):
	session = request.POST.get('session')
	myclass = request.POST.get('myclass')
	term = request.POST.get('term')
	subject = request.POST.get('subject')
	t = Term.objects.get(term=term)
	s = Session.objects.get(date=session)
	sub = Subject.objects.get(subject_name=subject)

student/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required

from student.models import FeedbackModel




@login_required(login_url='/accounts/login/')
def Student(request):
	return render(request, 'stu/index.html') 


@login_required(login_url='/accounts/login/')
def feedbackView(request):
	if request.method == 'POST':
		feedback = request.POST.get('feedback')
		title = request.POST.get('title')
		mode = request.POST.get('mode')
		FeedbackModel.objects.create(user=request.user, feedback=feedback, title=title, mode=mode)
	qs = FeedbackModel.objects.filter(user=request.user)
	context = {'qs':qs}
	return render(request, 'stu/feedback.html', context)

@login_required(login_url='/accounts/login/')
def createFeedback(request):
	if request.method == 'POST':
		feedback = request.POST.get('feedback')
		title = request.POST.get('title')
		mode = request.POST.get('mode')
		FeedbackModel.objects.create(user=request.user, feedback=feedback, title=title, mode=mode)
		return redirect("student:feedback")
	return render(request, 'stu/create_feedback.html')

@login_required(login_url='/accounts/login/')
def deleteFeedback(request, id):
	qs = FeedbackModel.objects.get(id=id, user=request.user).delete()
	return redirect("student:feedback")

templates/administrator/addpayment.html
{% extends 'administrator/base.html' %}
{% load crispy_forms_tags %}
{% block text %}

<div class="row">
<div class="col-md-6 col-md-offset-3">
<center><h2>Add Payment</h2></center>
<form method="post">
	{% csrf_token %}
	{{form|crispy}}


	<button type="submit" class="btn btn-primary ">Submit</button> 
</form>	
</div>
</div>
{% endblock %}

templates/administrator/addpaymentsuccess.html
{% extends 'administrator/base.html' %}
{% load crispy_forms_tags %}
{% block text %}
<title>  Password Successfully Changed | atreat4u</title>
<div class="container">
<div class="row">
    <div class="col-md-6 col-sm-offset-3">
        <hr>
        <center><h4 style="font-family: 'black_jackregular';"><i class="fa fa-paper-plane" aria-hidden="true" style="color: orange"></i>&nbsp;{% if messages %}
<ul class="messages">
{% for message in messages %}
<li class="{{ message.tags }} well">{{ message }}</li>
{% endfor %}
</ul>
{% endif %}</h4></center><br>
        <hr>
        <p>
         <center><p>Click on the button below to Add Payment</p></center>
<a href="{% url 'administrator:addpayment' %}"><button type="button" class="btn btn-md btn-block" style="background-color: rgb(123, 197, 26); color: white;"><i class="fa fa-paper-plane-o" aria-hidden="true"></i>&nbsp;Add Payment</button></a>
    
     </p>
    <br>
    <hr>
</div>
 <div class="col-md-6">
 <br>
 <br>
 <br>

 </div>
</div>
</div>
{% endblock %}

templates/administrator/checkpayment.html
{% extends 'administrator/base.html' %}
{% block text %}
{% load crispy_forms_tags %}
{% load static %}


<input style="visibility: hidden;" id='myToken' name="" value="{{csrf_token}}">
<div class="col-sm-12">
<div class="container-fluid">

<p>
	Session: {{s}}<br>
	Class: {{current_class}}<br>
	Term: {{t}}<br>
</p>


  <table class="table table-condensed">
    <thead>
      <tr>
        <th>Surname</th>
        <th>Middle Name</th>
        <th>First Name</th>
        <th>Reg Number</th>
        <th>Session</th>
        <th>Term</th>
        <th>Class</th>
		<th>Purpose</th>
		<th>Fee</th>


        <th></th>


      </tr>
    </thead>
    <tbody>

      {% for i in qs %}
      <tr>
          <td>{{i.student.surname}}</td>
          <td>{{i.student.middle_name}}</td>
          <td>{{i.student.first_name}}</td>
          <td><a href="{% url 'administrator:edit_payment' i.id %}"><span id="{{i.id}}">{{i.student.Registration_Number}}</span></a></td>
          <td>{{i.current_session}}</td>
          <td>{{i.current_term}}</td>
          <td>{{i.current_class}}</td>
		<td>{{i.purpose}}</td>
		<td>{{i.fee}}</td>

      </tr>
      {% endfor %}
    </tbody>


  </table>

 <!--  <button class="btn btn-primary btn-lg">Generate Position</button> -->




 <form action="{% url 'administrator:generate_course' %}" method="POST">{% csrf_token %}

<table>
  <tr>
    <td>





    </td>

  </tr>
</table>

</form>


</div>
</div>
















{% endblock %}

templates/administrator/generatepin.html
{% extends 'administrator/base2.html' %}

{% block body %}
Select details
<form action="{% url 'administrator:pin' %}" method="POST">{% csrf_token %}
Select class:
    <select name='select_class' style="width: 150px;">
      <option>kg1</option>
      <option>kg2</option>
      <option>kg3</option>
      <option>kg1</option>
      <option>pry1</option>
      <option>pry2</option>
      <option>pry3</option>
      <option>pry4</option>
      <option>pry5</option>
      <option>pry6</option>
      <option>jss1</option>
      <option>jss2</option>
      <option>jss3</option>
      <option>sss1</option>
      <option>sss2</option>
      <option>sss3</option>
    </select>

Select session:

    <select name='select_session' style="width: 150px;">
	{% for i in session %}
      <option>{{i.date}}</option>
     {% endfor %}
    </select>

   <input type="submit" value="Go">

</form>




{% endblock %}

templates/administrator/index.html
{% extends 'administrator/base.html' %}
{% load static %}

{% block body %}
    <div id="wrapper">

        {% include 'administrator/sidebar.html' %}
        {% block shortcut %}
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Welcome {{request.user.username}}...</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">

                <div class="col-lg-4 col-md-6">
                    <div class="panel panel-green">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-home fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <!-- <div class="huge">12</div> -->
                                    <div> Go to Home</div>
                                </div>
                            </div>
                        </div>
                        <a href="{% url 'home:home' %}">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>


                <div class="col-lg-4 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-plus fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <!-- <div class="huge">26</div> -->
                                    <div>View Student Reviews</div>
                                </div>
                            </div>
                        </div>
                        <a href="{% url 'administrator:feedback' %}">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>

                <div class="col-lg-4 col-md-6">
                    <div class="panel panel-yellow">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-arrows fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                  <!--   <div class="huge">124</div> -->
                                    <div>Publications</div>
                                </div>
                            </div>
                        </div>
                        <a href="{% url 'administrator:news' %}"">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <!-- <div class="col-lg-3 col-md-6">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-check fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    
                                    <div>Generate Position</div>
                                </div>
                            </div>
                        </div>
                        <a href="{% url 'administrator:generate_result' %}">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div> -->

                <!-- <div class="col-lg-3 col-md-6">
                    <div class="panel panel-green">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-home fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    
                                    <div>Exam</div>
                                </div>
                            </div>
                        </div>
                        <a href="{% url 'home:home' %}">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div> -->


                <!-- <div class="col-lg-3 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-plus fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    
                                    <div>Time Table</div>
                                </div>
                            </div>
                        </div>
                        <a href="{% url 'administrator:register' %}">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div> -->


            </div>
            {% endblock shortcut %}

            {% block text %}
            {% endblock %}

        </div>

        <!-- /#page-wrapper -->

    </div>

{% endblock %}

templates/administrator/select_payment.html
{% extends 'administrator/base.html' %}
{% block text %}
{% load crispy_forms_tags %}
{% load static %}


<input style="visibility: hidden;" id='myToken' name="" value="{{csrf_token}}">
<div class="col-sm-12">
<div class="container-fluid">

<p>
<h3>Results for <b style="color: red">{{detail}}</b> in <b style="color: red">{{searched}}</b> </h3>
</p>

 
  <table class="table table-condensed">
    <thead>
      <tr>
        <th>Surname</th>
        <th>Middle Name</th>
        <th>First Name</th>
        <th>Reg Number</th>
        <th>Session</th>
        <th>Term</th>
        <th>Class</th>
    <th>Purpose</th>
    <th>Fee</th>
<th>Date</th>

        
        <th></th>


      </tr>
    </thead>
    <tbody>
    
      {% for i in qs %}
      <tr>
          <td>{{details.surname}}</td>
          <td>{{details.middle_name}}</td>
          <td>{{details.first_name}}</td>
          <td><a href="{% url 'administrator:edit_payment' i.id %}"><span id="{{i.id}}">{{i.Registration_Number}}</span></a></td>
          <td>{{i.current_session}}</td>
          <td>{{i.current_term}}</td>
          <td>{{i.current_class}}</td>
    <td>{{i.purpose}}</td>
    <td>{{i.fee}}</td>
 <td>{{i.created}}</td>

      </tr>
      {% endfor %}
    </tbody>


  </table>

 <!--  <button class="btn btn-primary btn-lg">Generate Position</button> -->




 <form action="{% url 'administrator:generate_course' %}" method="POST">{% csrf_token %}

<table>
  <tr>
    <td> 


    
 
     
    </td>
   
  </tr>
</table>
  
</form>


</div>
</div>
















{% endblock %}

templates/administrator/select_student.html
{% extends 'administrator/base.html' %}
{% block text %}
{% load crispy_forms_tags %}
{% load static %}


<input style="visibility: hidden;" id='myToken' name="" value="{{csrf_token}}">
<div class="col-sm-12">
<div class="container-fluid">



  </p>
  <table class="table table-condensed">
    <thead>
      <tr>
        <th>Surname</th>
        <th>Middle Name</th>
        <th>First Name</th>
        <th>Reg Number</th>
        <th>Session</th>
        <th>Term</th>
        <th>Class</th>
  
        
        <th></th>


      </tr>
    </thead>
    <tbody>
    
      {% for i in qs %}
      <tr>
          <td>{{i.surname}}</td>
          <td>{{i.middle_name}}</td>
          <td>{{i.first_name}}</td>
          <td><a href="{% url 'administrator:edit_student' i.id %}">{{i.Registration_Number}}</a></td>
          <td>{{i.current_session}}</td>
          <td>{{i.current_term}}</td>
          <td>{{i.current_class}}</td>

      </tr>
      {% endfor %}
    </tbody>


  </table>

 <!--  <button class="btn btn-primary btn-lg">Generate Position</button> -->




 <form action="{% url 'administrator:generate_course' %}" method="POST">{% csrf_token %}

<table>
  <tr>
    <td> 


    
 
     
    </td>
   
  </tr>
</table>
  
</form>


</div>
</div>
















{% endblock %}